// Generated by CoffeeScript 1.7.1
var Base,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.Editor || (window.Editor = {});

Base = (function() {
  function Base() {
    this.startUp();
  }

  return Base;

})();

Editor.CommandBox = (function(_super) {
  __extends(CommandBox, _super);

  function CommandBox() {
    this.render = __bind(this.render, this);
    this.startUp = __bind(this.startUp, this);
    return CommandBox.__super__.constructor.apply(this, arguments);
  }

  CommandBox.prototype.element = "#menu";

  CommandBox.prototype.startUp = function() {
    return this.render();
  };

  CommandBox.prototype.render = function(html) {
    return $(this.element).html(Editor.Templates.render("menu"));
  };

  return CommandBox;

})(Base);

Editor.Application = (function(_super) {
  __extends(Application, _super);

  function Application() {
    this.startUp = __bind(this.startUp, this);
    return Application.__super__.constructor.apply(this, arguments);
  }

  Application.prototype.startUp = function() {
    return new Editor.CommandBox;
  };

  return Application;

})(Base);
