// Generated by CoffeeScript 1.7.1
var templates,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

window.Editor || (window.Editor = {});

templates = (function() {
  function templates() {
    this.render = __bind(this.render, this);
  }

  templates.prototype.render = function(name, params) {
    var k;
    if (params == null) {
      params = {};
    }
    return k = this[name](params);
  };

  templates.prototype.menu = _.template('<div id="command-box" onClick="this.contentEditable=\'true\';">\n</div>');

  return templates;

})();

Editor.Templates = new templates;
