// Generated by CoffeeScript 1.6.3
var LiveJS,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

LiveJS = {};

LiveJS.User = (function() {
  User.prototype.name = null;

  function User(name) {
    this.name = name;
    this.setName = __bind(this.setName, this);
    this.getName = __bind(this.getName, this);
  }

  User.prototype.getName = function() {
    return this.name;
  };

  User.prototype.setName = function(name) {
    this.name = name;
  };

  return User;

})();

LiveJS.fileExplorer = (function() {
  fileExplorer.prototype.user = null;

  function fileExplorer(user) {
    this.user = user;
    this.showCreateUser = __bind(this.showCreateUser, this);
    this.toggle = __bind(this.toggle, this);
    this.getFolder = __bind(this.getFolder, this);
    this.showSaveCall = __bind(this.showSaveCall, this);
    this.execute = __bind(this.execute, this);
    this.userExists = __bind(this.userExists, this);
  }

  fileExplorer.prototype.userExists = function() {
    if (this.user) {
      if (this.user.getName()) {
        return true;
      }
    }
    return false;
  };

  fileExplorer.prototype.execute = function() {
    var reult;
    reult = this.userExists();
    if (reult) {
      return this.showSaveCall();
    } else {
      return this.showCreateUser();
    }
  };

  fileExplorer.prototype.showSaveCall = function() {
    return this.getFolder(this.user.getName());
  };

  fileExplorer.prototype.getFolder = function(name) {
    return $.ajax({
      url: "gears/getContents.php",
      method: "GET",
      data: {
        user: this.user.getName()
      },
      success: (function(_this) {
        return function(list) {
          list = tmpl(template.get('files'), {
            files: list
          });
          $("#filedialog").html(list);
          return _this.toggle();
        };
      })(this)
    });
  };

  fileExplorer.prototype.toggle = function() {
    $("#filedialog").fadeToggle();
    return $("#mycan").fadeToggle();
  };

  fileExplorer.prototype.showCreateUser = function() {
    return this.user = new LiveJS.User("Ramu");
  };

  return fileExplorer;

})();
